services:
  backend:
    image: ken027/ratelimiter-api
    container_name: ratelimiter-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7.4-alpine
    container_name: ratelimiter_cache
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
